chores clean up
ClickHouse/clickhouse-go pull request #1036
Opened 2023-07-24 05:19 UTC by cxiang03

## Summary
Chores Example Codes Improve

## Checklist
- [x] Unit and integration tests covering the common scenarios were added
- [x] A human-readable description of the changes was provided to include in CHANGELOG

2023-07-24 05:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ClickHouse/clickhouse-go?pullRequest=1036) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ClickHouse/clickhouse-go?pullRequest=1036) before we can accept your contribution.<br/><hr/>**Caleb Xiang** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ClickHouse/clickhouse-go?pullRequest=1036) it.</sub>

2023-08-02 12:26 UTC, jkaflik commented
Thanks @cxiang03 . This will go with the next minor release.

2023-08-10 07:21 UTC, jkaflik requested changes
this introduces a bug

2023-08-10 07:21 UTC, jkaflik commented on examples/std/compression.go
> +			, Col2 Uint64
```suggestion
			, Col2 UInt64
```

2023-08-10 08:38 UTC, cxiang03 commented
> this introduces a bug

🫣 applied

2023-08-10 08:40 UTC, cxiang03 commented on examples/std/compression.go
> +			, Col2 Uint64
```suggestion
			, Col2 UInt64
```

2023-08-10 10:24 UTC, jkaflik approved these changes

2023-10-26 13:58 UTC, merged