Implement release connection in batch
ClickHouse/clickhouse-go pull request #1062
Opened 2023-08-07 13:19 UTC by EpicStep

With this change, you can append to the batch directly without using helper structures (slice). Earlier this led to an empty pool, although it is not necessary to keep the connection in the batcher for the append operation.

In our implementation we saved about 2GB of memory per pod.

<img width="1361" alt="screen" src="https://github.com/ClickHouse/clickhouse-go/assets/36516357/d383b378-d8f3-4029-ac80-2dfdf2667531">

Close #1047

2023-08-08 08:06 UTC, jkaflik requested changes
Thanks for your contribution. I understand the need for this; however not sure if we should expose `ReleaseConnection`, but do it for the user instead. This might be overhead for short-live batches. 

Lets address comments and think if this approach is clean.

Fewer API functions we expose, the more clarity in the usage.

2023-08-08 08:06 UTC, jkaflik commented on tests/batch_release_connection_test.go
> +	require.Error(t, batch.ReleaseConnection())
nit: assert error type/message

2023-08-08 08:06 UTC, jkaflik commented on tests/batch_release_connection_test.go
> +	require.Error(t, batch.ReleaseConnection())
nit: assert error type/message

2023-08-08 09:47 UTC, EpicStep commented
I agree with you. I think we can add options in `PrepareBatch` (it won't break backwards compatibility).
Example: `PrepareBatch(context.Background(), "INSERT INTO some_table", WithReleaseConnection())`

2023-08-09 17:17 UTC, EpicStep commented
@jkaflik Thanks. I added this feature to README.md

2023-08-09 17:19 UTC, EpicStep commented
When will these changes be released?

2023-08-10 06:55 UTC, jkaflik approved these changes

2023-08-10 07:08 UTC, jkaflik commented
@EpicStep I plan to release it today. In a merge train, your PR is last and has conflicts. It's easy, but it would be great if you push from your fork.

2023-08-10 07:17 UTC, EpicStep commented
@jkaflik Yes, I can merge

2023-08-10 08:02 UTC, EpicStep commented
@jkaflik done :)

2023-08-10 08:06 UTC, merged