HTTP Part 0
ClickHouse/clickhouse-go pull request #610
Opened 2022-06-15 07:20 UTC by ortyomka

Issue #597 

### STD Driver Extension
STD driver haven't depended on specific implementation.
Interface will be chosen depends on `Options` in connect stage.

### New connection
HTTP connection was added with minimum functionality (Open, Ping, Close).
Other functions return `ErrHttpNotSupported` for now. Their implementation will be in the next PRs.

### Tests
Added tests for HTTP connection through STD interface.

### Breaking changes
None. All tests passed successfully.

cc @gingerwizard

2022-06-15 07:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ClickHouse/clickhouse-go?pullRequest=610) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ClickHouse/clickhouse-go?pullRequest=610) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ClickHouse/clickhouse-go?pullRequest=610) it.</sub>

2022-06-15 08:59 UTC, gingerwizard commented
This looks extremely promising and an elegant solution @ortyomka Tests are failing as we need to update the container to expose http.

2022-06-15 09:00 UTC, gingerwizard commented
See https://github.com/ClickHouse/clickhouse-go/blob/v2/.github/workflows/run-tests.yml#L34

2022-06-15 09:29 UTC, ortyomka commented
I have exposed HTTP port for tests

Could you run the tests again? 
@gingerwizard

2022-06-17 10:42 UTC, gingerwizard requested changes
Minor naming changes. This LGTM - i prefer `transport` over `layer` if possible.

2022-06-17 10:42 UTC, gingerwizard commented on clickhouse_std.go
> +type layer interface {
can we call this `transport`?

2022-06-17 10:42 UTC, gingerwizard commented on clickhouse_std.go
> +func (std *nativeLayer) Ping(ctx context.Context) error { return std.conn.ping(ctx) }
likewise `nativeTransport`

2022-06-17 10:42 UTC, gingerwizard commented on clickhouse_std.go
> +type httpLayer struct {
see above, maybe `httpTransport`

2022-06-17 10:42 UTC, gingerwizard commented
@ortyomka minor naming change otherwise happy to merge ASAP.

2022-06-17 10:53 UTC, ortyomka commented
@gingerwizard, done

2022-06-17 10:53 UTC, gingerwizard commented
Great start, thanks @ortyomka

2022-06-17 10:53 UTC, merged