feat: support for map[string]interface{} / []map[string]interface{} and some types can be converted to int64/uint64 with no loss of precision
ClickHouse/clickhouse-go pull request #794
Opened 2022-10-22 15:16 UTC by DGuang21

To some extent, it is supported that some types can be converted to int64/uint64 with no loss of precision, and that reads and writes to incoming map[string]interface / []map[string]interface are supported.

The code may still need to be optimized, and this is only the first version

2022-10-26 09:33 UTC, gingerwizard commented
@DGuang21 not comfortable with the warnings although I can potentially see they might not occur.

I think you only want to support this for the uint64 and in64 types not all of them - for this you'll need to have conditional check in the gen code.

2022-10-26 12:06 UTC, DGuang21 commented
> @DGuang21 not comfortable with the warnings although I can potentially see they might not occur.
> 
> I think you only want to support this for the uint64 and in64 types not all of them - for this you'll need to have conditional check in the gen code.

Regarding the code warning, I will fix it after the discussion, don't worry

Because there are only simple modifications here, my purpose is to support the writing and reading of map[string]interface. At present, the uint/int/string conversion is modified so that, for example, when the database type is map[string]int64, I can define map[string]interface in Golang to write instead of having to specify map[string]int64. This seems a little unfriendly.

Of course, the commonly used types are more than this. Whether it can be modified in this way, and which types need to be compatible, can only be developed after your approval. This can currently be understood as a demo.

The reason for this modification is to define and generate related model / dao files more conveniently in the ORM scaffolding without having to generate a specific type.

2022-11-21 12:02 UTC, gingerwizard commented
Ok @DGuang21 i think i see what you're trying to achieve. Currently maps and slices must be strongly typed on insert and you want flexibility. Makes sense. If you want to rework this to avoid errors i'll review properly and we can move forward with the proposal.

2022-12-09 22:34 UTC, jkaflik commented
@DGuang21 can you have a look at the failing tests?

2022-12-11 15:09 UTC, DGuang21 commented
I'm very sorry, it's the end of the year now, and many employees of Chinese companies need to deal with their own promotions at the end of the year, and I am no exception.

I expect that I will be able to complete the remaining Fail CI Fix and logical supplements of this PR in January.

But the general logic and processing method should not change much, so if you have time, you can do a review first, then I can complete the fixes and code changes more quickly. grateful.

@jkaflik @gingerwizard

2022-12-12 17:38 UTC, jkaflik requested changes

2022-12-12 17:38 UTC, jkaflik commented on lib/column/column_gen.go
> -	switch v := v.(type) {
This file is code generated:
```
// Code generated by make codegen DO NOT EDIT.
// source: lib/column/codegen/column.tpl
```

2022-12-12 17:38 UTC, jkaflik commented on lib/column/map.go
> +		fmt.Println(types)
please remove unnecessary logging

2022-12-12 17:38 UTC, jkaflik commented on lib/column/map.go
> +	if value.Kind() == reflect.Map && col.row(i).Kind() == reflect.Map {
can we have a function extract with name explaining the logic?

2022-12-12 17:38 UTC, jkaflik commented on lib/column/tuple.go
> +	if value.Kind() == reflect.Map && field.Kind() == reflect.Map {
this code seems to be duplicated

2023-05-26 10:03 UTC, closed without merging