Closes #848 (quoted column name in INSERT INTO)
ClickHouse/clickhouse-go pull request #849
Opened 2022-12-13 19:49 UTC by wizzard0

Closes #848 by unquoting column names similar to how the brackets are currently parsed %)

2022-12-13 20:28 UTC, jkaflik commented
@wizzard0 
Thanks for your contribution. Are you able to provide a test case that covers this issue? 
Reference: https://github.com/ClickHouse/clickhouse-go/blob/b78c9faca931f7df673c8f7b63ffba945e121502/tests/issues

2022-12-14 18:47 UTC, jkaflik requested changes
add a test case if possible

2022-12-15 10:39 UTC, wizzard0 commented
@jkaflik Sure, I'll get back to it a bit later, have to finish some other tasks rn

2022-12-22 16:55 UTC, jkaflik commented
@wizzard0 do you think you would be able to work on this soon?

2022-12-22 17:00 UTC, wizzard0 commented
@jkaflik I'm working thru backlog that's accumulated recently because of the blackouts in Kyiv. Don't want to make promises bc blackouts can easily return anytime. So yes I want to, but right now it's not really under my control.

2022-12-22 17:10 UTC, jkaflik commented
@wizzard0 absolutely, no pressure. I will try to have a look at it by myself in my spare time if needed.

2023-02-20 08:12 UTC, jkaflik commented
My bad. This was already fixed in https://github.com/ClickHouse/clickhouse-go/pull/829 and already reported in https://github.com/ClickHouse/clickhouse-go/issues/828. Closing it.

2023-02-20 08:12 UTC, closed without merging