add to  batchColumn  AppendRow and fix parseDate
ClickHouse/clickhouse-go pull request #922
Opened 2023-03-02 16:23 UTC by pikot

## Summary
-  fix integration test fail

```
--- FAIL: TestDate32 (0.01s)
    date32_test.go:81: 
                Error Trace:    /clickhouse-go/tests/date32_test.go:81
                Error:          Received unexpected error:
                                clickhouse: dateTime overflow. Col7 must be between 1925-01-01 and 2283-11-11
                Test:           TestDate32
```
error may hapened even if time string parsed without error

-  add to  batchColumn function AppendRow, 
usecase:
I have data in rows and want to use batch column insert. Logic with creating columns arrays, and  iterate  this array in Append, looks like overkill. Enouh iterate my data rows and call AppendRow without creating column arrays.

2023-03-02 16:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ClickHouse/clickhouse-go?pullRequest=922) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ClickHouse/clickhouse-go?pullRequest=922) before we can accept your contribution.<br/><hr/>**Ivan Ivanov** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ClickHouse/clickhouse-go?pullRequest=922) it.</sub>

2023-03-03 13:00 UTC, jkaflik requested changes

2023-03-03 13:00 UTC, jkaflik commented on lib/column/date.go
> +                err = dateOverflow(minDate, maxDate, tv, defaultDateFormatNoZone)
This line will never be reached. We do return in case err nil. 

We don't have tests for this error case.

2023-03-03 13:01 UTC, jkaflik commented
@pikot, thanks for your contribution!

2023-03-03 16:25 UTC, pikot commented on lib/column/date.go
> +                err = dateOverflow(minDate, maxDate, tv, defaultDateFormatNoZone)
ups, yes, my fault,  At first glans it looked easier, but I found! )  there is TIME ZONE Problem =)
vars
        minDate32, _ = time.Parse("2006-01-02 15:04:05", "1925-01-01 00:00:00")
        maxDate32, _ = time.Parse("2006-01-02 15:04:05", "2283-11-11 00:00:00")
has UTC time zone

but tv, according to code
```
       if tv, err = time.Parse(defaultDateFormatNoZone, value); err == nil {
                return time.Date(
                        tv.Year(), tv.Month(), tv.Day(), tv.Hour(), tv.Minute(), tv.Second(), tv.Nanosecond(), time.Local,
                ), nil
        }
```
has  time.Local, in my case MSK. 

Аnd date 1925-01-01 00:00:00 +0300 MSK is before date 1925-01-01 00:00:00 +0000 UTC, thats why tests failed


I tried to change Min/Max to
```
        minDate32, _ = time.ParseInLocation("2006-01-02 15:04:05", "1925-01-01 00:00:00", time.Local)
        maxDate32, _ = time.ParseInLocation("2006-01-02 15:04:05", "2283-11-11 00:00:00", time.Local)
```
but I have  problem, in test case - min value now has EET timezone -- 1925-01-01 00:00:00 +0200 EET 
at the same time max value, has good  timezone 2283-11-11 00:00:00 +0300 MSK

I don't know why, but I will find solution )

2023-03-06 19:15 UTC, closed without merging

2023-03-06 19:37 UTC, pikot commented on lib/column/date.go
> +                err = dateOverflow(minDate, maxDate, tv, defaultDateFormatNoZone)
I see fix for timezone bug. thanks! 
As I think - ETT timezone appears due to in 1925 MSK timezone doesn't exist.
I will recreate pull request.