support query distributed table with JSON column
ClickHouse/clickhouse-go pull request #956
Opened 2023-04-01 16:46 UTC by lrita

## Summary
Support query distributed table with JSON column. When distributed table with JSON column, clickhouse not return `Tuple` column as query result. e.g. with table:

```sql
CREATE TABLE xxx.xx_log_cl
(
    `log_time` DateTime64(3, 'Asia/Shanghai'),
    `log_type` String,
    `ip` String,
    `client_ip` String,
    `id` String,
    `request_id` String,
    `category` String,
    `service_type` Int32,
    `logs` Object('json')
)
ENGINE = Distributed('cluster_1', 'xxx', 'xx_log', rand())
```

current code crash with:
```
panic: Not implemented [recovered]
	panic: Not implemented

goroutine 12 [running]:
testing.tRunner.func1.2({0xbdba20, 0xe90eb0})
	/Users/yanqing11/dev/go/src/testing/testing.go:1389 +0x24e
testing.tRunner.func1()
	/Users/yanqing11/dev/go/src/testing/testing.go:1392 +0x39f
panic({0xbdba20, 0xe90eb0})
	/Users/yanqing11/dev/go/src/runtime/panic.go:838 +0x207
github.com/ClickHouse/clickhouse-go/v2/lib/column.(*JSONObject).ScanRow(0xc00070f8e8?, {0xbbedc0?, 0xc000236740?}, 0x40d7e5?)
	/Users/yanqing11/dev/app/src/github.com/ClickHouse/clickhouse-go/lib/column/json.go:856 +0x27
github.com/ClickHouse/clickhouse-go/v2.scan(0xc0000302c0, 0x1, {0xc000010120?, 0x9, 0xbbed01?})
	/Users/yanqing11/dev/app/src/github.com/ClickHouse/clickhouse-go/scan.go:82 +0x1ab
github.com/ClickHouse/clickhouse-go/v2.(*rows).Scan(0xbbedc0?, {0xc000010120?, 0x10?, 0xcebc7e?})
	/Users/yanqing11/dev/app/src/github.com/ClickHouse/clickhouse-go/clickhouse_rows.go:75 +0xa5
github.com/ClickHouse/clickhouse-go/v2/tests.TestMultipleJSONRows(0xc0006c29c0)
	/Users/yanqing11/dev/app/src/github.com/ClickHouse/clickhouse-go/tests/json_test.go:317 +0x222d
testing.tRunner(0xc0006c29c0, 0xda9400)
	/Users/yanqing11/dev/go/src/testing/testing.go:1439 +0x102
created by testing.(*T).Run
	/Users/yanqing11/dev/go/src/testing/testing.go:1486 +0x35f
```

## Checklist
Delete items not relevant to your PR:
- [ ] Unit and integration tests covering the common scenarios were added
  - I have no friendly way to create Distributed table in unit test with test docker container and extern clickhouse cluster. Then there is no uint test code commit.

2023-04-01 16:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ClickHouse/clickhouse-go?pullRequest=956) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ClickHouse/clickhouse-go?pullRequest=956) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ClickHouse/clickhouse-go?pullRequest=956) it.</sub>

2023-04-03 07:07 UTC, jkaflik commented
@lrita, thanks for your contribution. Can you please add test cases, at least with the happy path?

2023-04-04 05:12 UTC, jkaflik requested changes

2023-04-04 05:12 UTC, jkaflik commented on lib/column/json.go
> +	panic("bug")
what is exactly the case here? `Decode` func wasn't called prior?
let's make it more describtive

2023-04-04 05:13 UTC, jkaflik commented
@lrita please have a look at a test checks report. (please skip cloud tests, since it's expected to break for ppl outside org)

2025-02-07 01:13 UTC, SpencerTorres commented
The `Object('json')` type has been [deprecated](https://clickhouse.com/docs/en/sql-reference/data-types/object-data-type) and this portion of the code will soon be removed.

The [new JSON type](https://clickhouse.com/docs/en/sql-reference/data-types/newjson) in Go was added in: https://github.com/ClickHouse/clickhouse-go/pull/1455

2025-02-07 01:13 UTC, closed without merging